export const MODULE_NAME = 'LOGIN';

// TODO: YOU NEED TO CHANGE THIS CLIENT ID FOR A CUSTOM ONE.
//  ONCE THAT IS DONE YOU CAN CONFIGURE DIFFERENT PUBLIC URLS.
export const GOOGLE_CLIENT_ID='550680093505-99jvso0njjmhsu9n9bc3fiaqd9aseslf';
